# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0113ebbb5269650761296b1ce9cd0a0aefbfb6903795651bb5bee2213669946d39d9bfbeb3dd8fd8b3ad730a45e88d23c27b7fd807685910efaf8db529a1b514

test:
  secret_key_base: 7b33ec53f765862b40afa431e3a15d24f210a57fd6d509d78278926bed4bcd29fea8c60f43e4566c6548582e132499a3e985a509f97e9e143f052f530fdf501a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
